import "./globals.css";
import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";

import NavBar from "@/components/navbar";
import Footer from "@/components/footer";
import Script from "next/script";
import QueryProvider from "@/providers/query-provider";
import { PublicEnvScript } from "next-runtime-env";

import { ThemeProvider } from "@/components/theme-provider";

import { Toaster } from "@/components/ui/sonner";
import Ads from "@/components/ads";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const APP_NAME = "KagePlay";
const APP_DEFAULT_TITLE = "KagePlay - Watch Free Anime Online in HD";
const APP_DESCRIPTION = "KagePlay - Watch Free Anime Online in HD Quality. Stream anime free in HD with sub & dub options. Browse thousands of titles by genre, year, studio, and more. No ads, no bullshit.";
const APP_KEYWORDS = [
  "free anime streaming sites", "free anime online", "free anime apps", "free anime app",
  "free anime watch", "free anime watch site", "free anime website", "free anime websites",
  "free anime site", "free anime sites", "free anime streaming", "watch free anime",
  "watch free anime online", "free anime websites to watch", "best free anime sites",
  "best free anime websites", "where to watch free anime", "where can i watch anime for free",
  "where can i watch free anime", "where to watch anime for free", "where to watch anime free",
  "where to watch anime online free", "where to watch anime online for free",
  "where to watch anime for free online", "how to watch anime for free", "how to watch free anime",
  "is crunchyroll free to watch anime", "where to watch dubbed anime free",
  "where can i watch anime for free online", "what are some free anime websites",
  "hianime", "hi anime", "hianime website", "hianime safe", "is hianime safe",
  "hianime app", "hianime apk", "hianime login", "hianime discord", "hianime to",
  "hianime not working", "hianime not loading", "hianime down", "is hianime down",
  "hianime subtitles not working", "what happened to hianime", "hianime replacement",
  "hianime shutdown", "hianime shut down",
  "aniwatch", "aniwatch tv", "aniwatch apk", "aniwatch discord", "aniwatch alternatives",
  "aniwatch alternative", "sites like aniwatch", "websites like aniwatch", "is aniwatch safe",
  "is aniwatch down", "aniwatch down", "aniwatch not working", "aniwatch not loading",
  "aniwatch is down", "aniwatch not working 2025", "is aniwatch broken right now",
  "why is aniwatch not working",
  "anime", "anime world", "anime planet", "anime dekho", "anime wallpaper",
  "anime wallpaper 4k", "anime photo", "anime drawing",
  "hindi anime", "hindi anime zone", "animeflix hindi anime", "hindi anime website",
  "hindi anime dub", "hindi anime dubbed", "how to watch anime in hindi",
  "where to watch anime in hindi", "where can i watch anime in hindi",
  "where to watch anime in hindi for free", "how to watch anime in hindi for free",
  "how to watch anime for free in hindi", "where can i watch attack on titan anime in hindi",
  "which anime is available in hindi on netflix", "where to download anime in hindi",
  "crunchyroll free anime",
  "aniwave", "aniwave ru", "aniwaves ru",
  "kageplay", "kageplay anime",
  "anime streaming", "anime streaming site", "free anime streaming",
  "watch anime online", "watch anime free", "watch anime online free",
  "anime online", "free anime online",
  "stream anime", "anime stream",
  "anime site", "free anime site", "best anime site",
  "anime website", "free anime website", "best anime website",
  "anime community", "anime fans", "anime library", "massive library",
  "anime catalogue", "anime collection",
  "anime episodes", "anime episode", "new anime", "latest anime",
  "popular anime", "trending anime", "seasonal anime",
  "dubbed anime", "sub anime", "english dub",
  "anime genre", "action anime", "romance anime", "comedy anime",
  "thriller anime", "fantasy anime", "horror anime", "slice of life",
  "isekai anime", "mecha anime", "sports anime",
  "naruto", "naruto shippuden", "boruto",
  "one piece", "bleach", "bleach thousand year blood war",
  "attack on titan", "aot", "shingeki no kyojin",
  "jujutsu kaisen", "kaisen",
  "demon slayer", "kimetsu no yaiba",
  "death note", "solo leveling", "chainsaw man",
  "dragon ball", "dragon ball z", "dbz", "dragon ball super", "dbs",
  "my hero academia", "hero academia",
  "tokyo revengers", "vinland saga",
  "hell's paradise", "blue lock",
  "spy x family", "oshi no ko",
  "frieren", "frieren journey's end",
  "sakamoto days", "solo leveling",
  "jujutsu kaisen", "kaiju",
  "dandadan", "beastars",
  "baki hanma", "fire force",
  "classroom of the elite", "rezero",
  "jojo's bizarre adventure", "jojo",
  "fullmetal alchemist", "cowboy bebop",
  "high quality anime", "hd anime", "1080p anime",
  "anime server", "fast streaming server",
  "anime without ads", "ad free anime",
  "no sign up anime", "anime no registration",
  "anime app", "anime website 2026",
  "anime search", "search anime",
  "anime suggestions", "recommend anime",
  "anime list", "anime watchlist",
  "anime bookmark", "favorite anime",
  "anime request", "request anime",
  "report anime", "anime issues",
  "anime not loading", "anime buffering",
  "anime video player", "anime player",
  "anime mobile friendly", "anime responsive",
  "anime tablet", "anime phone",
  "anime laptop", "watch anime on laptop",
  "anime desktop", "anime pc",
  "anime offline", "download anime",
  "anime community forums", "anime social",
  "anime feedback", "feedback anime",
  "anime support", "support anime",
  "legal anime streaming", "official anime",
  "crunchyroll alternative", "funimation alternative",
  "9anime alternative", "zoro alternative",
  "kissanime alternative", "hianime alternative",
  "anime site 2026", "best anime site 2026",
  "where to watch anime", "where can i watch anime",
  "watch anime for free", "free streaming sites",
  "anime no ads", "anime without popups",
  "safe anime site", "secure anime streaming",
  "anime privacy", "anime safe browsing",
  "modern anime interface", "clean anime design",
  "anime user interface", "ui anime",
  "anime experience", "user experience anime",
  "anime internet", "web anime",
  "anime genre filter", "filter anime",
  "anime a to z", "all anime",
  "anime movies", "anime series",
  "anime ova", "anime specials",
  "anime ona", "anime tv",
  "anime season", "anime sequel",
  "anime prequel", "anime remake",
  "anime reboot", "anime adaptation",
  "manga adaptation", "light novel adaptation",
  "shonen anime", "shojo anime", "seinen anime",
  "josei anime", "kodomo anime",
  "anime for kids", "anime for adults",
  "anime for beginners", "anime for fans",
  "classic anime", "retro anime", "80s anime", "90s anime",
  "hidden gem anime", "underrated anime",
  "popular anime titles", "top anime",
  "top rated anime", "best anime",
  "anime ranking", "anime rating",
  "imdb anime", "mal anime",
  "myanimelist anime", "anilist anime",
  "anime planet", "anime news network",
  "anime release schedule", "airing anime",
  "weekly anime", "anime calendar",
  "anime countdown", "upcoming anime",
  "anime announcement", "new season anime",
  "anime opening", "anime ending",
  "anime ost", "anime soundtrack",
  "anime music", "anime songs",
  "anime art", "anime style",
  "anime animation", "anime studio",
  "studio ghibli", "ufotable", "kyoani",
  "mappa", "bones", "madhouse",
  "toei animation", "production ig",
  "anime voice actors", "seiyuu",
  "japanese voice", "english voice",
  "sub vs dub", "subbed anime", "dubbed anime",
  "anime sub", "anime dub",
  "anime hd", "anime full hd",
  "anime 4k", "anime quality",
  "anime 60fps", "smooth anime",
  "anime loading fast", "quick anime",
  "instant streaming", "play instantly",
  "click play", "hit play",
  "anime video", "anime media",
  "anime content", "stream content",
  "anime library constantly updated", "new episodes",
  "episode weekly", "same day as japan",
  "minimal delay", "fast upload",
  "automated anime system", "fully automated",
  "scan update", "content scan",
  "anime 2024", "anime 2025", "anime 2026",
  "current anime", "newest anime",
  "anime fans worldwide", "global anime",
  "millions of fans", "anime community worldwide",
  "anime experience smooth", "no lag",
  "lower resolution", "adjustable quality",
  "quality selector", "flexible quality",
  "fiber optic", "gigabit internet",
  "fast connection", "reliable streaming",
  "choose server", "server switch",
  "multiple servers", "best server",
  "isp friendly", "location based",
  "highway lanes", "single click switch",
  "invested in servers", "high performance",
  "no buffering", "buffer free",
  "ultimate immersion", "enemy buffering",
  "loading circle", "endless loading",
  "hate buffering", "worst experience",
  "stream doomer", "streaming experience",
  "best streaming experience",
  "watch party", "stream with friends",
  "anime sharing", "share anime",
  "social media anime", "anime social media",
  "avoid spoilers", "spoiler free",
  "anime community safe", "friendly community",
  "no registration needed", "no sign up",
  "anime free no payment", "no credit card",
  "free forever", "completely free",
  "anime no subscription", "no monthly fee",
  "anime no premium", "free premium features",
  "anime premium", "premium anime",
  "premium features", "no paywall",
  "binge watch", "binge watching",
  "watch entire series", "complete series",
  "anime marathon", "watch all episodes",
  "anime no limit", "unlimited streaming",
  "anime freedom", "watch anywhere",
  "anime on the go", "mobile anime",
  "wi fi needed", "family friendly",
  "watch in car", "long trip anime",
  "background watch", "casual viewing",
  "phone anime", "smartphone anime",
  "tablet anime", "laptop anime",
  "desktop anime", "all devices",
  "fully responsive", "responsive design",
  "modern design", "clean interface",
  "intuitive navigation", "easy to use",
  "user friendly", "simple navigation",
  "organized library", "logical organization",
  "effortless browsing", "natural scrolling",
  "feel natural", "browsing experience",
  "digital clutter free", "no clutter",
  "stripped down", "focused design",
  "enemy complexity", "simple and clean",
  "no confusing menus", "no flashing banners",
  "no pop ups", "pop up free",
  "ad light", "minimal ads",
  "acceptable ads", "non intrusive",
  "supports creators", "supports site",
  "server costs", "bandwidth costs",
  "keep site free", "free forever promise",
  "anime donations", "support anime",
  "anime patreon", "buy me coffee",
  "anime contributors", "help anime site",
  "anime built by fans", "for fans by fans",
  "passionate team", "anime lovers team",
  "dedicated to anime", "best for anime",
  "anime first", "anime focused",
  "no distractions", "pure anime",
  "watch experience", "viewing experience",
  "ultimate destination", "go to site",
  "number one anime", "top tier anime",
  "premium experience", "high end anime",
  "as good as crunchyroll", "better than netflix",
  "paid service quality", "free but premium",
  "hands down best", "best free option",
  "honestly best anime", "we're confident",
  "you'll love it", "try it now",
  "see for yourself", "check it out",
  "anime awaits", "your anime journey",
  "start watching", "begin your adventure",
  "dive into anime", "explore anime",
  "rabbit hole anime", "deep dive",
  "never run out", "endless content",
  "infinite anime", "always something new",
  "gems to discover", "hidden treasures",
  "retro classics", "modern masterpieces",
  "old school anime", "new age anime",
  "taste of anime", "all tastes",
  "mood based", "what to watch",
  "cooking anime", "yuri anime", "yaoi anime",
  "magical girls", "niche genres",
  "indie anime", "hidden indie gems",
  "mainstream hits", "bangers",
  "super popular", "cult classics",
  "seasonal hits", "weekly episodes",
  "latest season", "currently airing",
  "just finished", "completed series",
  "movie collection", "anime movies list",
  "feature length", "anime film",
  "theatrical release", "anime cinema",
  "short films", "anime shorts",
  "ona series", "original net anime",
  "ova series", "original video animation",
  "special episodes", "anime special",
  "bonus content", "extras",
  "director's cut", "extended edition",
  "anime genres list", "complete genres",
  "action packed", "thrilling",
  "heart warming", "emotional stories",
  "tear jerker", "makes you cry",
  "laugh out loud", "hilarious",
  "mind bending", "psychological thriller",
  "dark themes", "mature content",
  "light hearted", "feel good",
  "adventure awaits", "epic journey",
  "fantasy world", "magical realm",
  "sci fi future", "cyberpunk",
  "post apocalyptic", "dystopian",
  "historical setting", "samurai era",
  "modern day", "realistic fiction",
  "supernatural elements", "paranormal",
  "super powers", "abilities",
  "martial arts", "fighting",
  "tournament arc", "battle royal",
  "school life", "daily life",
  "workplace comedy", "office",
  "music anime", "idol anime",
  "dance anime", "performance",
  "food anime", "cooking battles",
  "travel anime", "journey across",
  "survival anime", "death game",
  "mystery anime", "detective",
  "courtroom anime", "legal drama",
  "military anime", "war strategy",
  "space opera", "mecha battles",
  "robot anime", "giant robots",
  "transformer like", "gundam series",
  "sword art", "magic system",
  "rpg anime", "game elements",
  "video game adaptation", "game based",
  "harem anime", "reverse harem",
  "love triangle", "romantic comedy",
  "friendship themes", "nakama power",
  "family bonds", "sibling love",
  "found family", "ragtag group",
  "character growth", "development",
  "redemption arc", "character driven",
  "plot twist", "unexpected ending",
  "satisfying conclusion", "well written",
  "anime for everyone", "all ages",
  "family safe", "kid friendly",
  "mature audiences", "18 plus",
  "parental guidance", "viewer discretion",
  "content warning", "trigger warning",
  "watch responsibly", "enjoy safely",
  "bookmark site", "save for later",
  "don't forget", "never lose",
  "your collection", "personal list",
  "track progress", "continue watching",
  "where I left off", "resume anime",
  "episode tracker", "auto resume",
  "watch history", "recently watched",
  "anime statistics", "watch stats",
  "hours watched", "anime dedication",
  "level up", "anime journey",
  "share with friends", "tell others",
  "spread the word", "grow community",
  "help us grow", "support the site",
  "word of mouth", "recommend to friend",
  "social share", "share button",
  "facebook anime", "twitter anime",
  "reddit anime", "discord anime",
  "instagram anime", "tiktok anime",
  "anime community discord", "join discord",
  "official discord", "community server",
  "get involved", "participate",
  "request features", "suggest improvements",
  "vote on anime", "community polls",
  "anime trivia", "fun facts",
  "anime quiz", "test knowledge",
  "anime news", "industry news",
  "announcements", "updates blog",
  "changelog", "what's new",
  "site updates", "new features",
  "bug fixes", "improvements",
  "known issues", "work in progress",
  "roadmap", "planned features",
  "coming soon", "future updates",
  "beta features", "experimental",
  "feedback welcome", "your opinion matters",
  "report bug", "found an issue",
  "contact us", "get in touch",
  "email support", "help center",
  "faq page", "frequently asked",
  "common questions", "quick answers",
  "troubleshooting", "help guide",
  "video not loading", "player issues",
  "server down", "site not working",
  "maintenance mode", "temporary issue",
  "back online", "fixed now",
  "we hear you", "listening to feedback",
  "community first", "you matter",
  "transparent", "honest about ads",
  "why ads", "keeping free",
  "how we operate", "our mission",
  "about us", "our story",
  "the team", "who we are",
  "our values", "what we stand for",
  "anime for all", "accessible to everyone",
  "no barriers", "free access",
  "open to all", "worldwide anime",
  "global community", "united by anime",
  "anime transcends", "borderless",
  "language options", "multi language",
  "english interface", "hindi support",
  "subtitle options", "multiple subs",
  "hindi dub", "tamil anime",
  "telugu anime", "regional language",
  "indian anime fans", "anime in india",
  "asian anime", "western anime fans",
  "europe anime", "anime everywhere",
  "24/7 streaming", "always available",
  "reliable uptime", "99% uptime",
  "fast cdn", "global servers",
  "optimized delivery", "fast loading",
  "lightweight site", "quick to load",
  "seo optimized", "search friendly",
  "discoverable content", "easy to find",
  "google anime search", "find on google",
  "anime recommendations", "similar shows",
  "if you like", "you might also like",
  "related anime", "more like this",
  "discover new", "expand your taste",
  "step out comfort zone", "try new genres",
  "anime bucket list", "must watch",
  "essential anime", "classics you need",
  "top 100 anime", "best of all time",
  "award winning", "critically acclaimed",
  "fan favorite", "crowd pleaser",
  "cult following", "underdog story",
  "sleeper hit", "surprisingly good",
  "overhyped", "actually worth it",
  "worth the hype", "lives up to reputation",
  "better than expected", "exceeded expectations",
  "let down", "disappointing",
  "love it or hate it", "divisive",
  "controversial opinion", "hot take",
  "unpopular opinion", "fight me",
  "anime debate", "discuss",
  "civil discussion", "respectful",
  "spoiler tags", "mark spoilers",
  "be considerate", "anime etiquette",
  "welcome newbies", "help newcomers",
  "veteran anime fans", "experienced weebs",
  "weeb culture", "otaku lifestyle",
  "anime merch", "figures",
  "cosplay inspiration", "dress up as",
  "anime conventions", "con season",
  "meet fellow fans", "in person events",
  "watch together", "sync play",
  "simulcast", "same time as japan",
  "simuldub", "dub same week",
  "english cast", "voice actors",
  "director interview", "behind scenes",
  "making of anime", "production notes",
  "anime industry", "business side",
  "manga origin", "source material",
  "light novel original", "webcomic adaptation",
  "game adaptation", "novel based",
  "original concept", "anime original",
  "no source material", "pure anime",
  "creator's vision", "author's intent",
  "faithful adaptation", "changes from source",
  "filler episodes", "canon content",
  "filler list", "skip filler",
  "anime pacing", "slow burn",
  "fast paced", "action packed",
  "character introduction", "arc start",
  "season finale", "cliffhanger",
  "next season confirmed", "renewed",
  "waiting for next season", "anticipation",
  "speculation", "fan theories",
  "predictions", "what happens next",
  "ending explained", "analysis",
  "deep meaning", "symbolism",
  "hidden details", "easter eggs",
  "re-watch value", "better second time",
  "aged well", "still holds up",
  "dated but good", "product of its time",
  "remake needed", "deserves reboot",
  "spiritual successor", "similar vibe",
  "inspired by", "homage",
  "reference library", "anime references",
  "cultural impact", "changed the industry",
  "pioneering anime", "first of its kind",
  "genre defining", "set the standard",
  "raised the bar", "new benchmark",
  "influenced many", "legacy",
  "timeless classic", "forever relevant",
  "generational anime", "passed down",
  "shared childhood", "nostalgia hit",
  "grew up with", "formative anime",
  "memory lane", "good old days",
  "back in the day", "remember when",
  "golden age", "silver age",
  "modern era", "current generation",
  "new wave", "fresh take",
  "revival", "comeback",
  "enduring popularity", "still loved",
  "decades later", "test of time",
  "for future generations", "preserve",
  "anime archive", "historical value",
  "educational anime", "learn from",
  "cultural education", "japanese culture",
  "language learning", "learn japanese",
  "anime immersion", "natural learning",
  "subtitles help", "reading practice",
  "japanese audio", "authentic experience",
  "food in anime", "japanese cuisine",
  "travel inspiration", "visit japan",
  "anime locations", "real world places",
  "pilgrimage", "sacred spots",
  "japan travel guide", "anime tourism",
  "temples and shrines", "landmarks",
  "cityscapes", "rural japan",
  "seasonal beauty", "sakura season",
  "autumn leaves", "summer festival",
  "winter scenery", "snow anime",
  "beach episode", "summer vibes",
  "hot springs", "onsen episode",
  "school festival", "cultural festival",
  "sports day", "sports festival",
  "field trip", "class excursion",
  "beach vacation", "pool episode",
  "fireworks display", "hanabi",
  "new year episode", "traditions",
  "valentines anime", "christmas episode",
  "halloween special", "seasonal episodes",
  "themed episodes", "holiday spirit",
  "feel good episodes", "comfort anime",
  "healing anime", "iyashikei",
  "relaxing watch", "calm down",
  "decompress", "unwind",
  "stress relief", "mental health",
  "anime therapy", "feel better",
  "pick me up", "mood booster",
  "cozy anime", "warm hug",
  "gentle stories", "soft vibes",
  "aesthetic anime", "visually stunning",
  "art style", "unique animation",
  "beautiful backgrounds", "scenic views",
  "color palette", "vibrant colors",
  "muted tones", "moody atmosphere",
  "cinematography", "directing",
  "storyboarding", "key animation",
  "sakuga moments", "animation quality",
  "fluid motion", "smooth animation",
  "fight choreography", "well animated",
  "music composition", "bgm",
  "opening theme", "ending theme",
  "insert song", "character song",
  "soundtrack album", "score",
  "composer", "sound director",
  "voice direction", "casting choices",
  "fitting voices", "perfect cast",
  "iconic voice", "recognizable voice",
  "memorable performance", "stands out",
  "emotional delivery", "chills",
  "goosebumps", "teared up",
  "cried hard", "heartbreaking",
  "beautifully sad", "bittersweet",
  "happy tears", "emotional damage",
  "rent free", "lives in my head",
  "obsessed with", "can't stop thinking",
  "anime brainrot", "consumed by",
  "hyperfixation", "special interest",
  "deep dive into fandom", "fall down the rabbit hole",
  "fan content", "fan art",
  "fan fiction", "doujinshi",
  "amv", "anime music video",
  "edit", "tiktok edit",
  "youtube amv", "fan edit",
  "fan made", "community creations",
  "creative expression", "artists",
  "writers", "creators",
  "inspired by anime", "my art style",
  "drawing anime", "learn to draw",
  "anime tutorial", "art tips",
  "digital art", "traditional art",
  "sketching anime", "character design",
  "oc creation", "original character",
  "self insert", "fan character",
  "rpg inspiration", "dnd character",
  "campaign ideas", "roleplay",
  "world building", "lore creation",
  "writing help", "story inspiration",
  "character archetypes", "tropes",
  "anime tropes", "common themes",
  "predictable patterns", "refreshing subversion",
  "deconstruction", "played straight",
  "parody anime", "meta humor",
  "self aware", "fourth wall break",
  "comedy gold", "hilarious moments",
  "funny scenes", "comic relief",
  "laughter guaranteed", "smile maker",
  "wholesome content", "pure heart",
  "precious bean", "must protect",
  "soft character", "favorite boi",
  "favorite girl", "best boy",
  "best girl", "waifu",
  "husbando", "character crush",
  "love interest", "shipping",
  "canon ship", "otp",
  "side ship", "rare pair",
  "multi ship", "poly ship",
  "shipping wars", "peaceful shipper",
  "ship everyone", "cute together",
  "good chemistry", "enemies to lovers",
  "friends to lovers", "slow burn romance",
  "mutual pining", "confession episode",
  "first kiss", "love confession",
  "relationship goals", "couple goals",
  "married couple", "established relationship",
  "domestic bliss", "honeymoon phase",
  "healthy relationship", "green flags",
  "red flags", "toxic relationship",
  "redemption arc love", "healing together",
  "found family romance", "team as family",
  "friendship goals", "best friends",
  "ride or die", "through thick and thin",
  "brothers in arms", "sisterly bond",
  "sibling dynamic", "family saga",
  "parent child bond", "parental figure",
  "mentor mentee", "student teacher",
  "master apprentice", "training arc",
  "growth together", "mutual improvement",
  "rivalry", "friendly competition",
  "respect each other", "pushing limits",
  "becoming stronger", "self improvement",
  "never give up", "perseverance",
  "overcome obstacles", "face challenges",
  "inner strength", "believe in yourself",
  "power of friendship", "teamwork",
  "together we stand", "united we fall",
  "stand up again", "keep fighting",
  "never back down", "determination",
  "guts", "courage",
  "bravery", "heroism",
  "self sacrifice", "protect loved ones",
  "save the world", "become hero",
  "chosen one", "destiny",
  "fate", "prophecy",
  "ancient power", "awakening",
  "hidden potential", "unlock power",
  "power up", "transformation",
  "super saiyan", "bankai",
  "gear shift", "domain expansion",
  "cursed technique", "stand power",
  "nen ability", "haki awakening",
  "devil fruit", "quirk awakening",
  "magic system explained", "power scaling",
  "who would win", "versus debate",
  "power levels", "tier list",
  "anime battles", "best fights",
  "well choreographed", "epic showdown",
  "final battle", "climax fight",
  "emotional fight", "fateful duel",
  "one on one", "team battle",
  "boss fight", "final boss",
  "main villain", "antagonist",
  "sympathetic villain", "complex villain",
  "morally grey", "anti hero",
  "ends justify means", "villain redemption",
  "tragic backstory", "understand villain",
  "hero vs villain", "ideology clash",
  "philosophical debate", "moral dilemma",
  "hard choices", "sacrifices must be made",
  "no easy answers", "grey area",
  "thinking anime", "makes you think",
  "philosophical anime", "deep questions",
  "existential crisis", "meaning of life",
  "human condition", "society critique",
  "commentary", "satire",
  "dark humor", "tragicomedy",
  "bittersweet ending", "happy ending",
  "sad ending", "ambiguous ending",
  "open ending", "satisfying conclusion",
  "well executed", "perfect ending",
  "ruined ending", "disappointing finale",
  "stick the landing", "fell off",
  "strong start", "weak finish",
  "consistent quality", "gets better",
  "starts slow", "picks up",
  "give it time", "keep watching",
  "episode 3 rule", "three episode test",
  "worth continuing", "drop or keep",
  "should I watch", "is it good",
  "rating review", "honest opinion",
  "spoiler free review", "quick thoughts",
  "first impression", "initial reaction",
  "live reaction", "watching for first time",
  "blind watch", "no spoilers please",
  "reaction video", "react content",
  "anime tuber", "anime youtube",
  "anime streamer", "twitch anime",
  "vtuber anime", "virtual youtuber",
  "anime podcast", "discussion podcast",
  "weekly anime talk", "anime news show",
  "anime recommendations youtube", "top 10 lists",
  "anime iceberg", "deep dive video",
  "analysis video", "essay anime",
  "video essay", "long form content",
  "anime critique", "constructive criticism",
  "praise anime", "why it's good",
  "defense of", "underrated gem",
  "overrated popular", "hot take",
  "unpopular opinion video", "controversial takes",
  "agree to disagree", "respect opinion",
  "different tastes", "preferences",
  "no wrong way", "enjoy what you like",
  "gatekeeping", "let people enjoy",
  "elitism", "casual fan",
  "hardcore fan", "all are welcome",
  "inclusive community", "diverse opinions",
  "multicultural anime", "representation",
  "lgbtq anime", "queer characters",
  "gender bending", "non binary",
  "diverse cast", "different backgrounds",
  "cultural representation", "own voices",
  "authentic portrayal", "responsible depiction",
  "learning from anime", "window to culture",
  "bridge between worlds", "connecting people",
  "anime unites", "common ground",
  "language of anime", "universal themes",
  "love transcends", "shared humanity",
  "anime makes us human", "touches heart",
  "inspires change", "motivates me",
  "got me through", "helped me",
  "saved my life", "reason to keep going",
  "anime saved me", "thank you anime",
  "grateful for", "positive impact",
  "life changing", "forever grateful",
  "anime dad", "anime mom",
  "introduced my kids", "family bonding",
  "passing the torch", "next generation",
  "grew up with anime", "now my kids watch",
  "full circle", "beautiful cycle",
  "anime legacy", "continues",
  "long live anime", "forever weeb",
  "proud otaku", "wear it with pride",
  "no shame", "love what you love",
  "be yourself", "anime helped me be me",
  "found myself", "community acceptance",
  "safe space", "welcome all",
  "no judgment", "positive vibes only",
  "spread love", "anime love",
  "peace love anime", "wholesome community",
  "together we are", "stronger together",
  "united we stand", "power of community",
  "anime family", "we are family",
  "got your back", "support each other",
  "uplift each other", "grow together",
  "share joy", "celebrate together",
  "cry together", "laugh together",
  "experience together", "bond over anime",
  "more than a site", "it's home",
  "second home", "place to be",
  "my happy place", "sanctuary",
  "escape reality", "another world",
  "welcome home", "you belong here",
  "this is for you", "made with love",
  "heart and soul", "passion project",
  "labor of love", "built with care",
  "every detail", "thoughtful design",
  "we care", "you matter",
  "user first", "experience first",
  "constant improvement", "never settling",
  "always learning", "getting better",
  "evolving site", "growing with you",
  "your feedback shapes us", "co-created",
  "community driven", "by the people",
  "for the people", "democratic platform",
  "your voice heard", "we listen",
  "take action", "implement feedback",
  "visible changes", "we adapt",
  "agile development", "quick updates",
  "responsive team", "active development",
  "regular updates", "fresh content",
  "never stagnant", "always moving",
  "forward thinking", "innovation",
  "modern stack", "cutting edge",
  "best technology", "fast framework",
  "next gen streaming", "future ready",
  "web app", "pwa",
  "progressive web app", "installable",
  "add to home screen", "app like experience",
  "offline capable", "service worker",
  "cached content", "fast reload",
  "instant back", "snappy navigation",
  "smooth transitions", "delightful ux",
  "user delight", "surprise and delight",
  "small touches", "attention to detail",
  "polish", "refinement",
  "quality over quantity", "curated selection",
  "hand picked", "vetted content",
  "safe sources", "verified links",
  "proper attribution", "credit where due",
  "respect creators", "support official",
  "balanced approach", "both worlds",
  "convenience and ethics", "best of both",
  "ethical streaming", "responsible watching",
  "make informed choice", "you decide",
  "educate yourself", "know your options",
  "transparency", "open book",
  "no hidden agenda", "straightforward",
  "honest platform", "trustworthy",
  "build trust", "earn loyalty",
  "long term relationship", "here to stay",
  "not going anywhere", "committed",
  "dedicated team", "full time passion",
  "investing in future", "scalable platform",
  "growing library", "expanding reach",
  "more languages", "broader audience",
  "anime for everyone", "truly global",
  "breaking barriers", "language no obstacle",
  "subtitles in many languages", "dubbing options",
  "localized content", "regional favorites",
  "respecting cultures", "authentic experience",
  "accurate translations", "quality subs",
  "professional work", "fan level care",
  "best effort", "continuous improvement",
  "thank you for watching", "grateful audience",
  "we appreciate you", "you're the best",
  "none of this without you", "our reason",
  "keeps us going", "motivation",
  "your enjoyment", "our reward",
  "smile on your face", "worth it",
  "we did it", "together we built",
  "something special", "unique platform",
  "one of a kind", "stand out",
  "different approach", "better way",
  "reinventing anime streaming", "new standard",
  "setting trends", "leading by example",
  "inspiring others", "raising bar",
  "industry change", "ripple effect",
  "better anime ecosystem", "healthier community",
  "sustainable model", "long term vision",
  "future of anime streaming", "next chapter",
  "writing history", "being part of",
  "join us", "be part of story",
  "contribute", "get involved",
  "many ways to help", "every bit counts",
  "share your voice", "tell your story",
  "your experience matters", "unique perspective",
  "adds richness", "diverse tapestry",
  "beautiful community", "proud of what we built",
  "look how far we've come", "from dream to reality",
  "it started with an idea", "look at us now",
  "incredible journey", "and it continues",
  "best is yet to come", "stay tuned",
  "exciting future", "lots planned",
  "can't wait", "we're hyped",
  "you should be too", "get ready",
  "preparation underway", "something big coming",
  "teaser", "sneak peek",
  "coming attractions", "next level",
  "evolve and grow", "never stop",
  "relentless pursuit", "of perfection",
  "chase excellence", "settle for nothing less",
  "you deserve the best", "we give our best",
  "together we rise", "to new heights",
  "sky is not the limit", "beyond",
  "infinity and beyond", "to the moon",
  "dream big", "achieve together",
  "anime dream", "living the dream",
  "this is just the start", "beginning of something",
  "great things take time", "patience rewarded",
  "trust the process", "journey matters",
  "destination worth it", "promise",
  "we keep our promises", "deliver",
  "consistency", "reliability",
  "you can count on us", "dependable",
  "rock solid", "stable platform",
  "built to last", "foundation strong",
  "scalable architecture", "grows with you",
  "future proof", "ready for tomorrow",
  "tech forward", "always updated",
  "latest standards", "best practices",
  "security first", "your data safe",
  "privacy respected", "no tracking",
  "minimal data", "just enough",
  "your privacy matters", "we protect it",
  "safe browsing", "secure connection",
  "https everywhere", "encrypted",
  "no shady scripts", "clean code",
  "audited regularly", "secure platform",
  "peace of mind", "worry free",
  "focus on anime", "we handle rest",
  "sit back", "relax",
  "enjoy the show", "that's all",
  "happy streaming", "enjoy your anime",
  "see you soon", "come back again",
  "always welcome", "door open",
  "24/7 available", "always here",
  "never sleeps", "always watching",
  "ready when you are", "at your service",
  "your anime journey awaits", "start now",
  "what are you waiting for", "dive in",
  "the water's fine", "join us",
  "begin today", "start streaming",
  "one click away", "don't wait",
  "time is now", "seize the day",
  "carpe diem anime", "make today anime day",
  "every day is anime day", "live laugh anime",
  "anime is life", "life is anime",
  "breathe anime", "live it",
  "fully immersed", "in the zone",
  "anime state of mind", "zen",
  "find your flow", "lose track of time",
  "time flies", "when watching anime",
  "episode after episode", "just one more",
  "famous last words", "one more episode",
  "it's 3am", "worth it",
  "no regrets", "would do again",
  "anime sleep schedule", "who needs sleep",
  "anime addiction", "healthy obsession",
  "better than drugs", "natural high",
  "pure euphoria", "bliss",
  "heavenly experience", "divine comedy",
  "god tier anime", "peak fiction",
  "absolute cinema", "masterpiece",
  "work of art", "magnum opus",
  "in a league of its own", "untouchable",
  "stand above rest", "cream of the crop",
  "elite anime", "premium content",
  "top shelf", "best of best",
  "crème de la crème", "crème",
  "finest selection", "curated excellence",
  "pick of the litter", "choice cuts",
  "prime anime", "main event",
  "featured content", "spotlight",
  "editor's pick", "staff recommended",
  "community choice", "fan voted",
  "award winners", "critics choice",
  "audience favorite", "peoples choice",
  "viewer's discretion", "advisory",
  "explicit content", "nsfw",
  "mature rating", "age restricted",
  "parental lock", "safety features",
  "child friendly", "family filter",
  "content moderation", "responsible curation",
  "community guidelines", "rules",
  "be nice", "respect others",
  "no hate", "zero tolerance",
  "positive space", "bully free",
  "safe for all", "inclusive environment",
  "diversity celebrated", "all identities welcome",
  "equality matters", "stand with",
  "allyship", "support marginalized",
  "amplify voices", "listen and learn",
  "we stand together", "united against hate",
  "love is love", "anime for everyone",
  "no exceptions", "truly open",
  "our doors are open", "come as you are",
  "you are valid", "you are loved",
  "you are enough", "welcome exactly as you are",
  "no judgment here", "safe space anime",
  "authentic self", "be you",
  "proudly weeb", "otaku pride",
  "nerd culture", "embrace it",
  "nerd is the new cool", "geek chic",
  "intelligent entertainment", "smart storytelling",
  "complex narratives", "layered plots",
  "rich themes", "depth and substance",
  "more than cartoons", "serious art",
  "legitimate medium", "respect anime",
  "treat with respect", "dignity",
  "art form", "expression",
  "cultural treasure", "japan's gift",
  "shared heritage", "world treasure",
  "cherish and protect", "nurture the community",
  "water the garden", "help it bloom",
  "grow together", "flourish",
  "beautiful ecosystem", "symbiotic relationship",
  "fans and creators", "mutual appreciation",
  "support the art", "enable creation",
  "cycle of creativity", "inspiration leads to creation",
  "fan art inspires", "original works",
  "derivative works", "homage",
  "living tradition", "ever evolving",
  "anime is not static", "always changing",
  "adapting times", "relevant",
  "speaks to each generation", "new meanings",
  "rediscovered", "reinterpreted",
  "fresh eyes", "new perspective",
  "old favorites", "new discoveries",
  "endless cycle", "beautiful loop",
  "anime time loop", "groundhog day anime",
  "time travel", "chronological order",
  "watch order", "proper sequence",
  "release order", "story order",
  "chronological vs release", "debate",
  "how to watch", "guide",
  "beginner's guide", "where to start",
  "starter anime", "gateway anime",
  "entry point", "first anime",
  "what should I watch first", "recommendations for beginners",
  "ease into it", "start gentle",
  "deep end", "go hard",
  "jump right in", "trial by fire",
  "no wrong answer", "trust your gut",
  "follow your instinct", "pick what interests",
  "you do you", "your journey your pace",
  "no rush", "take your time",
  "savor each show", "let it marinate",
  "sit with it", "process",
  "reflect", "think about it",
  "discuss with others", "share thoughts",
  "written review", "rate anime",
  "star rating", "score out of 10",
  "your opinion counts", "rate what you watch",
  "build your list", "curate your collection",
  "proud of your taste", "develop your palate",
  "refined taste", "acquired taste",
  "guilty pleasure", "no guilt just pleasure",
  "enjoy unapologetically", "like what you like",
  "defend your favorites", "with passion",
  "reasoned arguments", "civil debate",
  "agree to disagree", "mature discussion",
  "enrich each other", "broaden horizons",
  "try something new", "step outside comfort",
  "surprise yourself", "you might like it",
  "don't knock it till you try it", "give it a chance",
  "first episode rule", "three episodes",
  "sometimes takes time", "slow build",
  "rewarding payoff", "trust the creators",
  "they know what they're doing", "seasoned professionals",
  "years of experience", "craft perfected",
  "dedicated artists", "passionate creators",
  "blood sweat and tears", "their love shines through",
  "appreciate the craft", "notice the details",
  "background art", "music composition",
  "voice direction", "everything matters",
  "holistic experience", "greater than sum",
  "magic of anime", "indescribable",
  "you know it when you feel it", "that feeling",
  "chills down spine", "goosebumps",
  "hair stands up", "jaw drops",
  "eyes wide", "can't look away",
  "glued to screen", "edge of seat",
  "biting nails", "holding breath",
  "intense focus", "complete absorption",
  "lost in the world", "transported",
  "escapism at its finest", "another reality",
  "visit another world", "experience different life",
  "live vicariously", "through characters",
  "feel their joy", "share their pain",
  "empathy machine", "understanding others",
  "build compassion", "see different perspectives",
  "windows into souls", "human connection",
  "we are not so different", "universal emotions",
  "laugh together", "cry together",
  "anime connects us", "to ourselves",
  "to each other", "to humanity",
  "profound experience", "life affirming",
  "reminds us why we're here", "to feel",
  "to love", "to grow",
  "to become better", "anime inspires",
  "be the hero", "of your own story",
  "your journey starts now", "take the first step",
  "we believe in you", "you got this",
  "never give up", "keep moving forward",
  "that's what anime taught us", "lessons for life",
  "wisdom from animation", "surprising depth",
  "from cartoons to philosophy", "unexpected teacher",
  "classroom of life", "anime sensei",
  "the real treasure", "was the friends we made",
  "along the way", "journey before destination",
  "anime proverb", "words to live by",
  "inspirational quotes", "motivational speeches",
  "character development", "real life application",
  "become your best self", "self improvement arc",
  "training arc irl", "level up",
  "grind never stops", "keep pushing",
  "limits are meant to be broken", "break through",
  "transcend your limits", "plus ultra",
  "go beyond", "plus ultra anime",
  "my hero academia plus ultra", "plus ultra",
  "exceed expectations", "prove them wrong",
  "show them what you got", "believe in yourself",
  "not because it's easy", "because it's hard",
  "that's what makes it worthwhile",
];

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#282A36",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://kageplay.saugii650.workers.dev"),
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: "%s | KagePlay",
  },
  description: APP_DESCRIPTION,
  keywords: APP_KEYWORDS,
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
  },
  manifest: "/manifest.json",
  formatDetection: {
    telephone: false,
  },
  alternates: {
    canonical: "https://kageplay.saugii650.workers.dev",
  },
  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: APP_DEFAULT_TITLE,
    description: APP_DESCRIPTION,
    url: "https://kageplay.saugii650.workers.dev",
    locale: "en_US",
    images: [
      {
        url: "/logo.png",
        width: 192,
        height: 192,
        alt: "KagePlay",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@kageplay",
    creator: "@kageplay",
    title: APP_DEFAULT_TITLE,
    description: APP_DESCRIPTION,
    images: ["/logo.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "c5KhVMd8GyPu1HuYMdWWXlyiYNlpFz2qrJ6LjEGFA2k",
  },
  category: "entertainment",
  other: {
    "charset": "UTF-8",
    "language": "en",
    "h1": APP_DEFAULT_TITLE,
    "links_count": "0",
    "images_count": "1",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://api.jikan.moe" />
        <link rel="preconnect" href="https://cdn.myanimelist.net" />
        <link rel="preconnect" href="https://image.tmdb.org" />
        <link rel="dns-prefetch" href="https://piratexplay.cc" />
        <link rel="dns-prefetch" href="https://api-js.piratexplay.cc" />
        <link rel="dns-prefetch" href="https://megaplay.buzz" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-C5ES6E3GFP"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-C5ES6E3GFP');`}
        </Script>
        <PublicEnvScript />
        <link rel="icon" href="/favicon.png" type="image/png" sizes="192x192" />
      </head>
      <body
        className={`${geistSans.className} antialiased max-w-[100vw] overflow-x-hidden`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <NavBar />
            <main id="main-content" role="main">
              {children}
              <Ads />
            </main>
            <Footer />
          </QueryProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
